#pragma once

#include <3ds/types.h>

typedef u8 MapColor;
enum {
	MAPCOLOR_NONE = 0,
	MAPCOLOR_GRASS,
	MAPCOLOR_SAND,
	MAPCOLOR_WOOL,
	MAPCOLOR_FIRE,
	MAPCOLOR_ICE,
	MAPCOLOR_METAL,
	MAPCOLOR_PLANT,
	MAPCOLOR_SNOW,
	MAPCOLOR_CLAY,
	MAPCOLOR_DIRT,
	MAPCOLOR_STONE,
	MAPCOLOR_WATER,
	MAPCOLOR_WOOD,
	MAPCOLOR_QUARTZ,
	MAPCOLOR_COUNT
};

extern const u32 COLORS[MAPCOLOR_COUNT];