name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build 3DSCraft (Code)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install g++ gcc make wget tar -y
      - name: Build makerom
        run: |
          git clone https://github.com/3DSGuy/Project_CTR
          cd Project_CTR
          
          make progs

          mkdir -p ../tools
          sudo cp makerom/bin/makerom /usr/bin/
          cd ..
      - name: Build bannertool
        run: |
          git clone https://github.com/carstene1ns/3ds-bannertool
          cd 3ds-bannertool
          cmake .
          make
          sudo cp bannertool /usr/bin/
          cd ..
      - name: Build game code
        id: build
        run: |
          make WORKFLOW=1 DEBUG=0
          make WORKFLOW=1 DEBUG=0 cia
          make WORKFLOW=1 DEBUG=1
          make WORKFLOW=1 DEBUG=1 cia
          mkdir exe
          mv 3DSCraft.3dsx exe
          mv 3DSCraft.cia exe
          mv 3DSCraft-debug.3dsx exe
          mv 3DSCraft-debug.cia exe
      - name: Upload Release 3DSX
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: 3DSCraft Roms
          path: ./exe/
